spring:
  datasource:
    url: jdbc:mysql://host.docker.internal:3306/bot?useSSL=false&serverTimezone=GMT&allowPublicKeyRetrieval=true
    username: bot
    password: Me6BDcAkaPJE3cc8
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: redis
    port: 6379
  cache:
    ehcache:
      config: classpath:ehcache.xml

logging:
  level:
    root: info

mybatis:
  type-aliases-package: top.feiyangdigital.entity
  mapper-locations: classpath:top/feiyangdigital/mapper/*.xml